### ISSUE TITLE
"Erkennbar machen", dass man sich gerade im Adminbereich befindet

### ISSUE THREAD

**Issue by MaaxGr** [SimonHaas/schulanmeldung#46]
anderer Hintergrund/Text/Button oder sonstiger Hinweis. Hofmann meinte, ja dass man besser erkennen soll, ob man sich im Backend befindet oder nicht.

**Comment by Glaciare** [comment]
habe die Überschrift geändert, reicht das?

**Comment by MaaxGr** [comment]
Nice. Ja. Das passt 👍
